# Generated by Django 6.0.3 on 2026-05-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('livro', 'Livro'), ('artigo', 'Artigo'), ('podcast', 'Podcast'), ('documentario', 'Documentário')], max_length=20, verbose_name='Tipo de conteúdo')),
                ('categoria', models.CharField(choices=[('ansiedade', 'Ansiedade'), ('depressao', 'Depressão'), ('burnout', 'Burnout'), ('estresse', 'Estresse'), ('autoconhecimento', 'Autoconhecimento'), ('bem_estar', 'Bem-estar'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('autor', models.CharField(blank=True, max_length=150, verbose_name='Autor')),
                ('url', models.URLField(blank=True, verbose_name='Link externo')),
                ('duracao', models.CharField(blank=True, max_length=20, verbose_name='Duração')),
                ('imagem_url', models.URLField(blank=True, verbose_name='URL da imagem de capa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
    ]
