# Generated by Django 6.0.3 on 2026-03-24 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='resetpasswordtoken',
            table=None,
        ),
    ]
