# Generated by Django 6.0.3 on 2026-03-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_resetpasswordtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
