# Generated by Django 6.0.3 on 2026-05-06 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('READ', 'Leitura'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação de Dados'), ('LGPD_ACEITE', 'Aceite LGPD'), ('LGPD_EXCLUSAO', 'Solicitação de Exclusão LGPD'), ('RESET_SENHA', 'Redefinição de Senha')], max_length=20, verbose_name='Ação realizada')),
                ('modelo', models.CharField(help_text='Nome do modelo Django que foi alterado', max_length=100, verbose_name='Modelo/Entidade afetada')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do objeto')),
                ('descricao', models.TextField(help_text='Detalhes sobre o que foi feito', verbose_name='Descrição da ação')),
                ('dados_anteriores', models.JSONField(blank=True, help_text='Snapshot dos dados antes da alteração (JSON)', null=True, verbose_name='Dados anteriores')),
                ('dados_novos', models.JSONField(blank=True, help_text='Snapshot dos dados após a alteração (JSON)', null=True, verbose_name='Dados novos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['usuario', '-data_hora'], name='auditoria_l_usuario_40b4c8_idx'), models.Index(fields=['acao', '-data_hora'], name='auditoria_l_acao_f052d0_idx'), models.Index(fields=['modelo', '-data_hora'], name='auditoria_l_modelo_ddc30c_idx')],
            },
        ),
    ]
