# Generated by Django 6.0.3 on 2026-05-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_empresa_aceitou_lgpd_empresa_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_predicao', models.DateTimeField(auto_now_add=True)),
                ('nivel_risco_predito', models.CharField(choices=[('Baixo', 'Baixo - Sem risco significativo'), ('Médio', 'Médio - Atenção necessária'), ('Alto', 'Alto - Acompanhamento recomendado'), ('Crítico', 'Crítico - Intervenção urgente')], max_length=20, verbose_name='Nível de risco predito')),
                ('probabilidade', models.FloatField(help_text='Confiança do modelo na predição (0.0 a 1.0)', verbose_name='Probabilidade da classe predita')),
                ('probabilidades_detalhadas', models.JSONField(blank=True, help_text='Probabilidade de cada nível de risco', null=True, verbose_name='Probabilidades por classe')),
                ('features_entrada', models.JSONField(blank=True, null=True, verbose_name='Features usadas na predição')),
                ('score_prioridade', models.FloatField(default=0.0, help_text='Score calculado para ordenação na fila do psicólogo (0-100)', verbose_name='Score de prioridade')),
                ('atendido', models.BooleanField(default=False, verbose_name='Foi atendido pelo psicólogo')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do atendimento')),
                ('observacoes_psicologo', models.TextField(blank=True, verbose_name='Observações do psicólogo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicoes', to='usuarios.funcionario')),
                ('psicologo_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicoes_atendidas', to='usuarios.psicologo')),
            ],
            options={
                'verbose_name': 'Predição ML',
                'verbose_name_plural': 'Predições ML',
                'ordering': ['-score_prioridade', '-data_predicao'],
            },
        ),
    ]
