# Generated by Django 6.0.2 on 2026-02-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('pontuacao_total', models.IntegerField(verbose_name='Pontuação total')),
                ('nivel', models.CharField(choices=[('bom', 'Bom - Nível saudável'), ('medio', 'Médio - Atenção necessária'), ('risco', 'Risco - Intervenção urgente')], max_length=10, verbose_name='Nível de saúde mental')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações geradas')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da pergunta')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('peso', models.IntegerField(default=1, help_text='Quanto mais importante, maior o peso', verbose_name='Peso na pontuação (1-5)')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do questionário')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='Resposta')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da resposta')),
            ],
        ),
    ]
