# Generated by Django 4.2.30 on 2026-05-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_empresa_aceitou_lgpd_empresa_atualizado_em_and_more'),
        ('questionarios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParecerPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(help_text='Análise profissional do psicólogo sobre a avaliação', verbose_name='Parecer clínico')),
                ('nivel_atencao', models.CharField(choices=[('rotina', 'Rotina - Acompanhamento padrão'), ('acompanhar', 'Acompanhar - Reavaliar em breve'), ('urgente', 'Urgente - Intervenção imediata')], default='rotina', max_length=15, verbose_name='Nível de atenção')),
                ('encaminhamento', models.TextField(blank=True, verbose_name='Encaminhamento / próximos passos')),
                ('necessita_acompanhamento', models.BooleanField(default=False, verbose_name='Necessita acompanhamento contínuo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='questionarios.avaliacao', verbose_name='Avaliação analisada')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='usuarios.psicologo', verbose_name='Psicólogo responsável')),
            ],
            options={
                'verbose_name': 'Parecer do Psicólogo',
                'verbose_name_plural': 'Pareceres dos Psicólogos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CheckinHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor', models.CharField(choices=[('bem', 'Bem'), ('triste', 'Triste'), ('ansioso', 'Ansioso'), ('cansado', 'Cansado'), ('motivado', 'Motivado')], max_length=20)),
                ('nota', models.IntegerField(choices=[(1, 'Muito baixo'), (2, 'Baixo'), (3, 'Neutro'), (4, 'Bom'), (5, 'Ótimo')], default=3, verbose_name='Nota de bem-estar (1 a 5)')),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_humor', to='usuarios.funcionario')),
            ],
            options={
                'verbose_name': 'Check-in de Humor',
                'verbose_name_plural': 'Check-ins de Humor',
                'ordering': ['-data'],
            },
        ),
    ]
